Feature/primera entrega
maxicaprioglio/Programacion_web_1 pull request #1
Opened 2024-08-22 19:46 UTC by maxicaprioglio

Buenas profe,
    Hago la primera entrega de la estructura de la web. Es una landigpage de una empresa de catering. Utilicé fotos y un logotipo que no son los definitivos, ya que habrá un cambio de imagen en el futuro, incluyendo un logo no real. Ademas, agregue etiquetas meta que no se si van a esta altura.

2024-08-22 21:18 UTC, MVelasquez98 commented on index.html
> +    <title>Document</title>
Es title corresponde al titulo que se ve en el encabezado de la pestaña del navegador. No corresponde "document", tiene que ser un nombre descriptivo del sitio

2024-08-22 21:27 UTC, MVelasquez98 requested changes
PUNTAJE POR CONSIGNA:

Estructura HTML (3 puntos):
Uso correcto de HTML5 para estructurar la página. ✔️
Completa inclusión de elementos básicos como título, párrafos, imágenes, enlaces, listas y tablas relacionados con el tema elegido. ❌
Introduce etiquetas semánticas pertinentes para mejorar la accesibilidad y el SEO. ✔️
GitHub (5 puntos):
Correcta creación de ramas "master" y "develop" en el repositorio. ❌ La rama que se creo es main, no master
Creación de una rama "feature/primera-entrega" y habilitación de GitHub Pages para esa rama. ✔️
Realización de commits necesarios sobre la rama de desarrollo. ✔️
Correcta creación de la pull request contra la rama "develop". ✔️
Entrega de la URL de la pull request y la URL generada por GitHub Pages. ✔️
Documentación (2 puntos):
Inclusión de comentarios claros y concisos en el código HTML. ✔️
Realizar una descripción y overview del proyecto elegido en el readme.md del repositorio ✔️
Nota: 8 (Ocho)

2024-08-22 21:27 UTC, MVelasquez98 commented on index.html
> +        <section id="viandas">
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar formularios, que bien podría usarse aca un formulario de compra por ejemplo

2024-08-22 21:27 UTC, MVelasquez98 commented on index.html
> +        <section id="servicios">
La actividad solicita:
"Incluye elementos básicos como título, párrafos, imágenes, enlaces, listas, formularios y tablas relacionados con tu tema."
Falta utilizar formularios, que bien podría usarse aca un tabla de servicios por ejemplo

2024-08-28 20:46 UTC, maxicaprioglio commented on index.html
> +    <title>Document</title>
@MVelasquez98 cambio realizado

2024-08-28 20:48 UTC, maxicaprioglio commented on index.html
> +        <section id="viandas">
@MVelasquez98 agrege una tabla para luego hacer card de productos.

2024-08-28 20:49 UTC, maxicaprioglio commented on index.html
> +        <section id="servicios">
@MVelasquez98 realice un formulario para cotizar el servicio de catering

2024-08-31 00:25 UTC, maxicaprioglio commented
@MVelasquez98

2024-09-01 16:45 UTC, MVelasquez98 approved these changes
LGTM

2024-09-02 19:51 UTC, merged