segunda entrega
maxicaprioglio/Programacion_web_1 pull request #2
Opened 2024-09-17 02:09 UTC by maxicaprioglio

@MVelasquez98  Ahi entrego la actividad 2.
La ire puliendo hasta que corrijas.

2024-09-25 15:01 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.
**Mejoras en la Maquetación CSS (5 puntos):**
- Implementación eficaz de diferentes tipos de selectores y aprovechamiento de la herencia de estilos para simplificar el código CSS. (1 punto) ✔️
- Aplicación correcta de formatos y fuentes para mejorar la legibilidad y estética del contenido, utilizando las propiedades CSS correspondientes. (1 punto) ✔️
- Uso adecuado de modelos de caja (box model) para controlar el tamaño, margen, relleno y bordes de los elementos de la página. (1 punto) ✔️
- Diferenciación clara entre elementos en línea y elementos en bloque mediante estilos CSS apropiados, demostrando comprensión de las diferencias y su aplicación en el diseño web. (1 punto) ✔️
- Implementación efectiva de columnas utilizando técnicas como elementos flotantes, display: flex y display: grid, según corresponda al diseño requerido. (1 punto) ❌ Falta el uso de Grid para la estructura de la pagina.

**Diseño de Columnas y Layouts Responsive (2 puntos):**
- Correcta utilización de media queries para crear un diseño responsive que se adapte de manera adecuada a diferentes tamaños de pantalla y dispositivos. (1 punto) ✔️
- Estructuración satisfactoria de layouts utilizando contenedores, filas y columnas, demostrando comprensión de los conceptos de diseño responsivo y su aplicación práctica. (1 punto) **Warning**  El formulario de contacto, no toma valores responsivos y esteticos

**GitHub (3 puntos):**
- Realización de commits necesarios sobre la rama de desarrollo utilizando Git. (1 punto) ✔️
- Creación de una rama "feature/segunda-entrega" a partir de la rama "develop" utilizando Git. (1 punto) ✔️
- Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "feature/primera-entrega" con "develop" en GitHub. (1 punto) ✔️

2024-09-25 15:07 UTC, MVelasquez98 commented on index.html
> +          <a href="https://wa.me/" target="_blank" rel="noopener noreferrer"
Interesante para avanzar sobre este boton https://faq.whatsapp.com/425247423114725/?locale=es_LA&cms_platform=iphone

2024-10-01 15:07 UTC, maxicaprioglio commented
@MVelasquez98  Ahi hice los cambios en whatsapp y en el formulario.

2024-10-01 18:53 UTC, MVelasquez98 approved these changes
LGTM

2024-10-01 19:06 UTC, merged