cambios 3ra entrega
maxicaprioglio/Programacion_web_1 pull request #6
Opened 2024-10-21 20:52 UTC by maxicaprioglio

Hago la 3 entrega.

2024-10-24 15:32 UTC, maxicaprioglio commented
Luego de ver la ultima Clase Ordene los Js por archivos que es lo que vi que no hice.
:)

2024-10-24 19:48 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA:**
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Algoritmos (1 punto)**
✅ 1 punto: Uso correcto y eficiente de algoritmos condicionales y ciclos.

- **Funciones (1 punto)**
❌ 0 puntos: Funciones con nombres confusos, estructura incorrecta o resultados incorrectos.

- **Funcionalidad (1 punto)**
✅ 1 punto: Flujo de trabajo completo y funcionalidad apropiada al contexto.  Código JavaScript correctamente referenciado y uso adecuado de prompt() y alert().

- **Interactividad (1 punto)**
✅ 1 punto: Interactividad adecuada y salidas coherentes.

- **Escalabilidad (1 punto)**
⚠️ 0.5 puntos:  Uso del todo no adecuado de funciones con parámetros, arrays y objetos o clases relevantes.

- **Legibilidad (1 punto)**
⚠️ 0.5 puntos: Nombres de variables, funciones u objetos poco significativos, código ilegible o mal estructurado. 

- **GitHub (4 puntos):**
✅ 1 punto: Creación de una rama "backport/primer-parcial" a partir de la rama "master" utilizando Git.
✅ 1 punto: Creación de una rama "feature/tercera-entrega" a partir de la rama "develop" utilizando Git.
⚠️ 0.5 puntos: Correcta realización de la solicitud de revisión para fusionar la rama "backport/primer-parcial" con "develop" en GitHub, resolviendo los conflictos de merge (si fuese necesario). No proporcionaste la url en la entrega
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama "release/primer-parcial" con "master" en GitHub, resolviendo los conflictos de merge (si fuese necesario).

**Nota**: 7 (Siete)

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/CarritoArray.js
Es un poco confuso que el archivo se llame CarritoArray, pero tiene principalmente un export class de Producto. En todo caso esto seria un clase Carrito, y tendrias otra clase Producto.

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/CarritoObjeto.js
> +let carrito = {};
No entiendo esta variable global de `carrito`, si hay otra `carritoArray` también

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/index.js
> +const carrito = new Producto();
¿Es un `carrito` o es un `producto`? Definir bien la responsabilidad de la [Clase](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes)

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/index.js
> +//usamos el carrito objeto
¿Por qué hay un "carrito objeto" y un "carrito Array"? ¿Por qué la separación?

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +    SolicitarDatos() {
Esta función es muy macro (tiene más de 100 lineas de código), llegaba a ser bastante ilegible en algún punto. Modularizar más.

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +      let valorEntrada = prompt(
Esta podría ser una función "Solicitar entrada"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +      let valorParrilla = prompt(
Esta podría ser una función "Solicitar parrilla"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +      let valorVegetariano = prompt(
Esta podría ser una función "Solicitar vegetariano"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +        "El servicio viene con: Pescados? no 'precione enter', si 'marque algo y presione enter' "
Esta podría ser una función "Solicitar pescados"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +      let valorMinutas = prompt(
Esta podría ser una función "Solicitar minutas"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +      let valorPizzas = prompt(
Esta podría ser una función "Solicitar pizzas"

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +export class FormularioServicio {
¿Hasta que punto es bueno una clase que solo tenga prompts? ¿Refiere realmente a una funcionalidad de negocio?¿No es preferible dejar esta responsabilidad al index, y que la clase se encargue de las operaciones propias de su responsabilidad como agregar, eliminar, actualizar, etc?

2024-10-24 19:48 UTC, MVelasquez98 commented on assets/js/FormularioServicio.js
> +        if (valorCantidad === "") {
Hay muchos if anidados, se te va escapar algún caso

2024-10-24 19:59 UTC, MVelasquez98 reviewed
No me proporcionaste la URL del backport en la entrega
![image](https://github.com/user-attachments/assets/19f46d74-95c7-40ea-a35c-69e3fbc12a1e)

2024-10-25 19:30 UTC, maxicaprioglio commented
Si cree dos opciones de carritos que estaba mal planteado. Realice cambios modularizando y nombrando bien las clases.

2024-11-15 19:50 UTC, maxicaprioglio commented
@MVelasquez98  Esperando la aprobacion para pasar a la siguiente entrega.

2024-11-15 20:07 UTC, MVelasquez98 commented
Tenes una review en pending aun

2024-11-16 14:54 UTC, maxicaprioglio reviewed
ahi deberia estar terminado.

2024-11-16 15:01 UTC, maxicaprioglio commented
> Tenes una revisión en pendiente aun

Comentarios estan todos resueltos y no encuentro que es elo que me falta revisar. Dejo print 
![image](https://github.com/user-attachments/assets/e24e1e21-f306-493b-ba0f-fe30cd5b1047)
![image](https://github.com/user-attachments/assets/c1e20fe6-4668-4bfd-8a8b-ac2b9649bdcc)
@MVelasquez98

2024-11-16 18:16 UTC, MVelasquez98 commented
<img width="565" alt="image" src="https://github.com/user-attachments/assets/75448915-5041-4241-80de-c0ff98b08766">

2024-11-16 18:45 UTC, maxicaprioglio commented
> <img alt="image" width="565" src="https://private-user-images.githubusercontent.com/43156596/386868882-75448915-5041-4241-80de-c0ff98b08766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODI4MzksIm5iZiI6MTczMTc4MjUzOSwicGF0aCI6Ii80MzE1NjU5Ni8zODY4Njg4ODItNzU0NDg5MTUtNTA0MS00MjQxLTgwZGUtYzBmZjk4YjA4NzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE4NDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMTA4MmNiZDZkNjZjODJiOTc2ZmYwODY4YTk0NzcwNDJkMDgzYTM2ZjUxNTY0MjBiNjQ2Y2Y3ODgxNTc1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.svozl87ebH300Nxs_kg4mpgFuN6jqeihv2WrPKGdBD4">

Bueno ahi buscando y buscando no encuentro ese cometario. por ahi lo borre o algo pero no lo veo. hice esos cambios realizados y dejo print de lo que veo yo cuando voy al archivo Carrito. 
![image](https://github.com/user-attachments/assets/08a7040d-adfd-4ad1-b83b-76716ed7cc9f)
@MVelasquez98

2024-11-16 21:52 UTC, MVelasquez98 approved these changes
LGTM

2024-11-17 02:41 UTC, merged