Release/segundo parcial
maxicaprioglio/Programacion_web_1 pull request #8
Opened 2024-11-28 15:33 UTC by maxicaprioglio

Entrega del segundo parcial. usando mock Api . @MVelasquez98

2024-11-28 16:19 UTC, maxicaprioglio commented
uhhh me falto agregar un then para agregar los click al cargar los productos y sacar el que esta al final. No hago el push porque ya entrege.
obtenerDatos....
.then(() => {
      const botones = document.querySelectorAll(".btn-enviar");
      botones.forEach((boton) => {
        boton.addEventListener("click", () => {
          const producto = new Producto(
            boton.dataset.id,
            boton.dataset.foto,
            boton.dataset.titulo,
            boton.dataset.precio
          );
          carrito.agregar(producto);
        });
      });
    })

2024-11-28 16:59 UTC, MVelasquez98 commented
Mientras este abierta la entrega en el campus podes subir los cambios necesarios, los cambios dejan de subirse cuando la entrega en el campus cierra

2024-12-01 21:14 UTC, MVelasquez98 commented
¿Por qué al pagar no se vacia el carrito?
![image](https://github.com/user-attachments/assets/1daae022-8f50-4156-a342-883a563c5f34)

2024-12-01 21:42 UTC, MVelasquez98 requested changes
**PUNTAJE POR CONSIGNA**:
La evaluación se realiza sobre una escala de 10 puntos, donde se aprueba con un mínimo de 4 puntos.

- **Asincronía y Manejo de Datos (3 puntos)**
✅ 1 punto: Utiliza AJAX y JSON para obtener datos de forma asíncrona, manejando adecuadamente promises y fetch para consumir alguna API mock .
✅ 1 punto: La información estática esta en formato JSON, se carga y utiliza de manera asíncrona.
✅ 1 punto: Recorrido de colecciones siendo óptimo utilizando funciones de orden superior. 

- **Gestión del Proyecto y Buenas Prácticas con GitHub (7 puntos)**:
✅ 1 punto: Realización de commits necesarios sobre la rama de desarrollo utilizando Git.
✅ 1 punto: Creación de una rama release/segundo-parcial a partir de la rama develop utilizando Git.
✅ 1 punto: Correcta realización de la solicitud de revisión y aprobación de la pull request para fusionar la rama feature/cuarta-entrega con develop en GitHub.
✅ 1 punto: Proporcionar la URL de la pull request y la URL generada por GitHub Pages para la rama release/segundo-parcial como parte de la entrega.
⚠️ 0.5 puntos: Implementa un archivo [CHANGELOG.md](https://github.com/Laboratoria/changelog-guide) documentando los cambios realizados en el proyecto en cada entrega o versión, siguiendo un formato estructurado. Revisa cambios propuestos, aún esta incompleto.
✅ 1 punto: Configura [reglas en GitHub](https://docs.github.com/es/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) para bloquear push directos a las ramas develop y master, exigiendo pull requests con al menos un revisor aprobado para realizar merges. Incluir en el comentario de la pull request una captura con el estado de las reglas.
❌ 0 puntos: No se implementa una [plantilla (template) de pull request](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) en el repositorio para estandarizar las solicitudes de revisión y asegurarse de incluir in[formación relevante](https://axolo.co/blog/p/part-3-github-pull-request-template) (descripción, cambios realizados, pruebas realizadas, etc.).  Agregar más detalles al respecto, tomar como modelo el ejemplo proporcionado

**Nota**: 8(Ocho)
**Comentario Final:**
¡Felicitaciones por tu buen desempeño en el simulador! Demostraste habilidad en el manejo asincrónico de datos y en la implementación de buenas prácticas en GitHub. Para el final, asegúrate de corregir las observaciones realizadas en la pull request. Ajustar el `CHANGELOG.md` y la implementación de una plantilla de pull request son áreas que pueden mejorarse y te darán ventaja adicional. Además, recorda revisar frecuentemente la consola para evitar errores que puedan afectar el funcionamiento de la aplicación. Con estos ajustes, de seguro te va ir muy bien en la entrega del examen final. ¡Segui con el buen trabajo!

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +    agregarClickBotonesCarrito();
Hay errores en consola:
![image](https://github.com/user-attachments/assets/2a7d855f-6501-4fc0-a4bd-32ce841663fd)

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +  sumar(id) {
Más especifico el nombre del método, ¿que seria `carrito.sumar`?

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +  descontar(id) {
Más especifico el nombre del método, ¿que seria `carrito.descontar`?

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +  eliminar(id) {
Más especifico el nombre del método, ¿que seria `carrito.eliminar`?

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Script.js
El nombre del archivo es **script.js** en camelCase, no en PascalCase **Script.js.**. Poque no se trata de una Clase

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Script.js
> +  return fetch(API_URL)
Usar async/await hace que el código sea más legible y fácil de seguir. Además, se maneja el error apropiadamente y el código no se corta a la mitad.
```suggestion
   try {
     const response = await fetch(API_URL);
     if (!response.ok) {
       throw new Error("Error al obtener los datos");
     }
     return await response.json();
   } catch (error) {
     throw error; // Propaga el error
   } finally {
     spinner.style.display = "none";
   }
```

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Script.js
> +const botones = document.querySelectorAll(".btn-enviar");
Evita la duplicación de código creando una función dedicada para agregar los event listeners a los botones. Esto hace que el código sea más fácil de mantener.
```suggestion
 function agregarEventListenerABotones() {
   const botones = document.querySelectorAll(".btn-enviar");
   botones.forEach((boton) => {
     boton.addEventListener("click", () => {
       const producto = new Producto(
         boton.dataset.id,
         boton.dataset.foto,
         boton.dataset.titulo,
         boton.dataset.precio
       );
       carrito.agregar(producto);
     });
   });
 }```

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Script.js
> +      const botones = document.querySelectorAll(".btn-enviar");
Evita la duplicación de código creando una función dedicada para agregar los event listeners a los botones. Esto hace que el código sea más fácil de mantener.

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Producto.js
> +  renderizarProductos(datos) {
Limpia el contenedor de productos antes de añadir nuevos elementos, especialmente si renderizarProductos puede ser llamado múltiples veces. Esto evitará la acumulación de duplicados en el DOM

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +          src="assets/img/productos/${producto.foto}.png"
Estas duplicando la extension .png, lo que hace que no encuentre la imagen:
![image](https://github.com/user-attachments/assets/27dfbf2d-01ca-45f8-a16d-e7e3c31e4352)
La extensión ya viene de la API con el nombre del archivo de la foto:
![image](https://github.com/user-attachments/assets/5d3a11ff-3920-4b4f-8b86-4a524aecfca4)

2024-12-01 21:42 UTC, MVelasquez98 commented on assets/js/Carrito.js
> +    document.getElementById("botonPagar").addEventListener("click", () => {
Asociar el evento del botonPagar una sola vez en el constructor mejora la eficiencia, en lugar de reasignarlo cada vez que se renderiza el carrito.
```suggestion
constructor() {
    // After initializing and loading carrito
    document.getElementById("botonPagar").addEventListener("click", () => {
        Swal.fire({
          title: "Compra",
          text: "Nos pondremos en contacto pronto.",
          icon: "success",
          confirmButtonText: "Gracias por su compra",
        });
        this.carrito = [];
        localStorage.removeItem("Carrito");
        this.actualizarCantidadAlCarritoVisual();
        this.renderizarProductosAlCarrito();
    });
}
```

2024-12-01 21:42 UTC, MVelasquez98 commented on CHANGELOG.md
No manejamos numero de versiones especificas en el proyecto, ordenalo por las fechas y entregas reales que hiciste en el proyecto:
Actividad obligatoria N°1
Actividad obligatoria N°2
Actividad obligatoria N°3
Actividad obligatoria N°4
Primer Parcial
Segundo Parcial

Linkea las pull request correspondientes

2024-12-01 21:42 UTC, MVelasquez98 commented on CHANGELOG.md
> +## [no publicados]
Se suele llamar [Unreleased]

2024-12-01 21:42 UTC, MVelasquez98 commented on CHANGELOG.md
> +- No se elimino archivos.
No se ponde entonces, solo agregas lo que hiciste

2024-12-01 21:42 UTC, MVelasquez98 commented on CHANGELOG.md
> +- se implemento un carrito funcional con las clases carrito y producto para el manejo de la compra de los productos (viandas).
Linkea las PR

2024-12-01 21:46 UTC, maxicaprioglio commented
> ¿Por qué al pagar no se vacia el carrito?
> ![image](https://github.com/user-attachments/assets/1daae022-8f50-4156-a342-883a563c5f34)
> 

Corregido.

2024-12-09 17:28 UTC, MVelasquez98 approved these changes
LGTM

2024-12-09 18:11 UTC, merged